### ISSUE TITLE
Incorrect AAD Redirect URL

### ISSUE THREAD

**Issue by mattosaurus** [Azure/api-management-developer-portal#299]
**Describe the bug**
I'm not sure if this is related to #298 or not but the AAD redirect URL appears to go to /signin rather than /signin-aad

**To Reproduce**
1. Add Azure Active Directory Identity to API Management Portal
2. Add "Sign in OAuth" widget to the signin page
3. Add redirect URL to AAD application, e.g. https://apimanagement.developer.azure-api.net/signin-aad
4. Attempt to sign in in new incognito window
5. Incorrect redirect URL error displayed
6. Add redirect URL to AAD application, e.g. https://apimanagement.developer.azure-api.net/signin
7. Attempt to sign in in new incognito window
8. Signin popup window signs in successfully but redirects back to itself

**Expected behavior**
On successful signin AAD pop up box redirects to signin-aad and user is authenticated

**Portal environment**
Managed

**Comment by ygrik** [comment]
I do not see any steps with publishing.
Did you publish your changes (Step 2. Add "Sign in OAuth" widget to the signin page)?

**Comment by mattosaurus** [comment]
Hi, yes I have published. Sorry, should probably have put that in the steps.

The URL of my developer portal is https://datofyapimanagement.developer.azure-api.net (it's just a test one).

An example of signing in and being redirected back to the sigin page can be seen in this image.

![developer-portal-signin](https://user-images.githubusercontent.com/22458485/68658775-faf13380-052d-11ea-9466-848dee0355bd.png)

This is with the following redirect URLs in my AAD application.

![developer-portal-aad-redirect-urls](https://user-images.githubusercontent.com/22458485/68659043-76eb7b80-052e-11ea-8917-90c1c8528407.png)

If I remove https://datofyapimanagement.developer.azure-api.net/signin (which is incorrect) leaving only https://datofyapimanagement.developer.azure-api.net/signin-aad (which is expected) then I recieve the following error on AAD login.

![developer-portal-aad-redirect-error](https://user-images.githubusercontent.com/22458485/68659307-eb261f00-052e-11ea-9383-bf72b7f610ad.png)

On inspecting the web traffic during the authentication process I can see that the incorrect redirect URL is specified in the GET request (I've removed a couple of the IDs).

https://login.microsoftonline.com/75f68947-86b7-49cb-a11f-ce4e49a85e6c/oauth2/v2.0/authorize?response_type=id_token&scope=openid%20email%20profile&client_id=****&redirect_uri=https%3A%2F%2Fdatofyapimanagement.developer.azure-api.net%2Fsignin&state=****&nonce=****&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.1.3&client-request-id=2e053fa4-5490-4c4f-87ff-aa2b4bc46522&response_mode=fragment

**Comment by azaslonov** [comment]
Hi @mattosaurus, thank you for reporting the issue. We're working on the fix.

**Comment by azaslonov** [comment]
Hi @mattosaurus, we updated Azure portal Identities blade to show Reply URL for new developer portal:
![image](https://user-images.githubusercontent.com/2320302/68901494-e5753880-06ea-11ea-9fa0-4e2e6ef02676.png)

Please note, there is another issue with AAD authentication which is going to be resolved by the end of this week.

**Comment by mike-urnun-msft** [comment]
Hi @azaslonov Although Azure Portal blade now provides a separate input field for Redirect URL, the value in it still appears to end with "signin" rather than "signin-aad" for me. OAuth flow (client_credential) also seems to be trying to use "signin" as well.
