### ISSUE TITLE
Footer doesn't stay where it belongs

### ISSUE THREAD

**Issue by BobbyCGD** [Azure/api-management-developer-portal#399]
## Bug description

1. Footer in the middle of the page, jammed up against content too small to fill the viewport.
    - There is no way to make the footer in the developer portal stay at the bottom of the page. 

2. Footer immobile and stuck to the bottom of the page on top of content that is taller than the page.
   - The only way to bring the footer down is to make it stick to the bottom. This is not ideal as it overlaps content on screen and is a problem if the footer is big. 

## Reproduction steps

1. Create a new page using default template
2. Visit new page

## Expected behavior

1. Footer at the bottom of the page, leaving space between it and short content.
2. Footer beneath the content even when the content is taller than the viewport.

## Is your portal managed or self-hosted?

Managed and Self-hosted

## Release tag or commit SHA (if using self-hosted version)

Using latest commit for self-hosted version.

## Additional information.
The image below illustrates the problem and the expected behaviour. 

![image](https://user-images.githubusercontent.com/9389935/72065460-2ac27a80-32d6-11ea-8a50-6b7edfea10b9.png)

**Comment by azaslonov** [comment]
Hi @BobbyCGD, yes, we're working on this, should be ready some time next week.

**Comment by azaslonov** [comment]
Fixed in #415.

**Comment by BobbyCGD** [comment]
Please reopen, the issue has returned.

**Comment by azaslonov** [comment]
Hi @BobbyCGD, did you use this option? I'm asking because I just checked it on one of my [test services].(https://alzasloneuap03.developer.azure-api.net/apis)

![image](https://user-images.githubusercontent.com/2320302/119571984-e9b1f580-bd66-11eb-96cc-6697c4a31400.png)

**Comment by BobbyCGD** [comment]
Hi, @azaslonov! Sorry I missed the notification. That did the trick for the footer! 

The menu is still broken... seems like there is an issue with the collapsible panel. It disappears completely in mobile view, even when I add a new collapsible panel in a new section.
