### ISSUE TITLE
Swagger validation which was working fine on 12th Feb is now failing validation for type: string, when it contains an example date as value

### ISSUE THREAD

**Issue by nachiketrss** [Azure/api-management-developer-portal#493]
Example Swagger/OpenAPI definition:
```yaml

                    "DateOfDelivery": {
                      "example": "2019-09-26",
                      "type": "string"
                    },
```

### Describe the bug you're encountering
The above is part of my swagger spec, and is getting validated ok in editor.swagger.io

We have release pipelines configured. The task 'API Management - Create or Update API' is used in the azure devops portal to configure the web api. The task's field 'Definition Artifact' is given the path of the swagger spec file.

The pipeline was running OK since November 2019 until around 12th Feb 2020. Since around 13th Feb we started to get validation errors when the pipeline runs.

Error:
```
2020-02-14T12:21:06.8150207Z Data and type mismatch found. [#/paths/~1order-product/post/responses/200/content/application~1json/schema/properties/DateOfDelivery/example]
@{code=ValidationError; target=representation; message=Parsing error(s): The input OpenAPI file is not valid for the OpenAPI specification https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md (schema https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v3.0/schema.yaml).}
```

### Expected behavior
No errors

**Comment by michaeltnguyen** [comment]
Hi, this is related to https://github.com/Azure/api-management-developer-portal/issues/294.  We had the same problem with date-only examples like you have.  The workaround is to have the type be a "date-time".  (this is wrong, but will allow your API to be imported).

The underlying bug is in Microsoft's implementation of OpenApi reader, which has gone unfixed for a very long time.

microsoft/OpenAPI.NET#407
microsoft/OpenAPI.NET#420 <-- specifically about dates
https://github.com/microsoft/OpenAPI.NET/issues/429

**Comment by nachiketrss** [comment]
Please note that when I change the OpenAPI in the version in the 'API Management - Create or Update API' task from 3.0 to 2.0, then everything works fine.

I am curious to know as to why it worked until around 12th Feb 2020?

**Comment by mikebudzynski** [comment]
Thanks for reporting the issue. Although we'll look into it, the problem is not related to the developer portal, so I'll be closing this thread. In future, please contact Azure support.

**Comment by VitaliyKurokhtin** [comment]
The issue is in APIM server side logic and should be resolved now.

**Comment by nachiketrss** [comment]
@VitaliyKurokhtin - can you give me more detail as to what caused the issue and how/when it got resolved please.

**Comment by VitaliyKurokhtin** [comment]
@nachiketrss this PR contains fix applied to APIM https://github.com/microsoft/OpenAPI.NET/pull/461

**Comment by brennerm** [comment]
Has the fix been deployed everywhere? I'm still having this issue.

**Comment by VitaliyKurokhtin** [comment]
The fix is still rolling out as a part of next release, depending on the region your ETA will vary. I can expedite things if you open support ticket with MS and problem description or share APIM service name.

**Comment by brennerm** [comment]
I opened a support ticket.
