### ISSUE TITLE
Array definitions are not displayed in the Developer portal

### ISSUE THREAD

**Issue by dgrospelier** [Azure/api-management-developer-portal#531]
## Bug description
When the API contains an array of objects, the item description of the array is not displayed in the Developer Portal.

## Reproduction steps
I have this definition in my Swagger:
`{
    "type": "object",
    "properties": {
        "Products": {
            "type": "array",
            "items": {
                "type": "object",
                "description": "products of the company",
                "properties": {
                    "productName": {
                        "type": "string",
                        "description": "name of the product"
                    }
                },
                "required": [
                    "productName"
                ]
            }
        }
    }
}`

I have an operation with a response associated with the type of this definition.

Unfortunately, the portal did not represent the definition of my object because it is an array:
![image](https://user-images.githubusercontent.com/10268596/76299389-4b4d8780-62bb-11ea-859c-b1b09d9757e1.png)

## Expected behavior
Expected behavior is the same as the legacy portal as shown below:
![image](https://user-images.githubusercontent.com/10268596/76299463-6ddfa080-62bb-11ea-9cb2-2aeb133383ac.png)

**Comment by LockTar** [comment]
Maybe related to #522

**Comment by dgrospelier** [comment]
> Maybe related to #522

Maybe, I don't know.

**Comment by azaslonov** [comment]
Hi @dgrospelier,
It shows `object[]` because there is no good way to display it in a table-like structure, which was designed to describe each field of the entity. Usually, this can be fixed by creating a separate type describing an array item and referencing it by `$ref` property.

It looks like what you want to do is to display a raw schema rather than breaking it down into types. It that right?

**Comment by mikebudzynski** [comment]
@dgrospelier I see your Issue translating into two things:

1. (bugfix) Our ability to flatten and display lists of objects as described above, for example `Products[].productName | string | name of the product`.
1. (feature request) An ability to switch between a table schema representation and JSON schema representation for any schema.

**Comment by createitreal** [comment]
I would love to have that feature as well: **the ability to switch between table schema and JSON schema representation**.

**Comment by azaslonov** [comment]
Fixed and deployed. Please re-publish the portal.

**Comment by dgrospelier** [comment]
Hi,
What is exactly the expected behaviour, because in my situation, here is what I see for my array in the dev portal (no changes regarding the initial issue):
![image](https://user-images.githubusercontent.com/10268596/84361365-d8122500-abcb-11ea-8771-58fdfd50e57b.png)

**Comment by LockTar** [comment]
I re-published our portal as well and I see the same as @dgrospelier

**Comment by dgrospelier** [comment]
Help please on this topic, the dev portal is still not able to display arrays successfully.

**Comment by mikebudzynski** [comment]
Can anyone provide reproduction steps? What's the input (OpenAPI file), expected behavior, and actual behavior?

**Comment by dgrospelier** [comment]
Here is a very simple swagger file with a simple "GET" operation and the definition of the response (an array of "Products"):
```
{
    "swagger": "2.0",
    "info": {
        "title": "TestAPI",
        "version": "1.0"
    },
    "host": "tobereplaced.azure-api.net",
    "basePath": "/testapi",
    "schemes": [
        "https"
    ],
    "securityDefinitions": {
        "apiKeyHeader": {
            "type": "apiKey",
            "name": "Ocp-Apim-Subscription-Key",
            "in": "header"
        },
        "apiKeyQuery": {
            "type": "apiKey",
            "name": "subscription-key",
            "in": "query"
        }
    },
    "security": [
        {
            "apiKeyHeader": []
        },
        {
            "apiKeyQuery": []
        }
    ],
    "paths": {
        "/": {
            "get": {
                "operationId": "get-all",
                "summary": "Get all",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/Products"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Products": {
            "type": "array",
            "items": {
                "required": [
                    "productCode",
                    "productName"
                ],
                "type": "object",
                "properties": {
                    "productCode": {
                        "type": "string"
                    },
                    "productName": {
                        "type": "string"
                    }
                }
            }
        }
    },
    "tags": []
}
```

You can see in the screenshot here below that the array is not displayed successfully in the Dev portal:
![image](https://user-images.githubusercontent.com/10268596/86324417-da9df280-bc3e-11ea-98d0-0770b7a2ac60.png)

**Comment by dgrospelier** [comment]
Any news on this issue @mikebudzynski?

**Comment by mikebudzynski** [comment]
No news at this moment. This issue is on our backlog, but we're prioritizing the items with the P0 label.

**Comment by adamstruck** [comment]
I would also like to see this issue fixed.

**Comment by mikebudzynski** [comment]
Acknowledged. We won't be able to address this issue before September though.
