### ISSUE TITLE
CORS Issue with new portal

### ISSUE THREAD

**Issue by AvanadeAPIClinicTeam** [Azure/api-management-developer-portal#55]
When we were trying to call any API from new  management portal we were getting below CORS Issue.

"**Unable to complete request
Since the browser initiates the request, it requires Cross-Origin Resource Sharing (CORS) enabled on the server.**"

**Comment by azaslonov** [comment]
This bug has been fixed. Please pull the latest version, cleanup and re-generate data.

**Comment by sealight** [comment]
When will this fix be deployed to the "managed portal"? 
i.e. <instance-name>.developer.azure-api.net

Is the managed portal much behind?

**Comment by azaslonov** [comment]
Hi @sealight, currently Test console in managed version makes only direct calls from the browser. However, you can [enable CORS policy](https://docs.microsoft.com/en-us/azure/api-management/api-management-cross-domain-policies#CORS) for your API to address that.

**Comment by sealight** [comment]
Hi @azaslonov, I did that, but I'm still getting this error: 
```
Unable to complete the request
Since the browser initiates the request, it requires Cross-Origin Resource Sharing (CORS) enabled on the server.
```

My inbound policy is
```
<inbound>
    <cors>
        <allowed-origins>
            <origin>*</origin>
        </allowed-origins>
        <allowed-methods>
            <method>GET</method>
            <method>POST</method>
            <method>PUT</method>
            <method>HEAD</method>
            <method>OPTIONS</method>
        </allowed-methods>
    </cors>
</inbound>
```

**Comment by azaslonov** [comment]
Hi @sealight, would you please try this one on API-level:
```
        <cors>
            <allowed-origins>
                <origin>*</origin>
            </allowed-origins>
            <allowed-methods>
                <method>GET</method>
                <method>POST</method>
                <method>OPTIONS</method>
                <method>DELETE</method>
                <method>PATCH</method>
                <method>PUT</method>
                <method>HEAD</method>
            </allowed-methods>
            <allowed-headers>
                <header>*</header>
            </allowed-headers>
            <expose-headers>
                <header>*</header>
            </expose-headers>
        </cors>
```

**Comment by sealight** [comment]
> Hi @sealight, would you please try this one on API-level:
> (...)

Many thanks @azaslonov ! It worked. So we need to allow the headers too. 

Which is the release governance for the "managed portal" (public) <custom>.developer.azure-api.net ? 
I mean: do you have continuous deploy with this github code repository? which branch? I would like to avoid self-hosting but if the managed portal is too far behind there's not much choice.

**Comment by mikebudzynski** [comment]
The managed version is usually updated within few days of the self-hosted version. The code is tracked internally, not through this repository.
