### ISSUE TITLE
Subscriptions are not correctly listed under the profile

### ISSUE THREAD

**Issue by JanneMattila** [Azure/api-management-developer-portal#616]
## Bug description

If you create new APIM instance and subscribe to product you cannot see subscription listed under profile.

## Reproduction steps

1. Go to Azure Portal and create new API Management instance e.g. 'worldsbestapim'
2. Publish new Developer portal
3. Sign up with new user using the newly published developer portal
4. Navigate to '/products' and subscribe product
5. Navigate to '/profile' page and you cannot see your new subscription

## Expected behavior

Expected to see list of subscriptions. (Note: These seem to be listed okay in old developer portal).

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

N/A

## API Management service name

worldsbestapim

## Environment

 - Operating system: Windows
 - Browser: Google Chrome, Edge

## Additional context

Browser console shows following error for `theme.js`:
```js
Uncaught (in promise) TypeError: Cannot read property 'displayName' of undefined
    at new exports.Product (theme.js:2)
    at theme.js:2
    at Array.map (<anonymous>)
    at exports.ProductService.<anonymous> (theme.js:2)
    at Generator.next (<anonymous>)
    at fulfilled (theme.js:2)
```

Code at line 32675 fails since `contract.properties` is `undefined`:

```js
, function(module, exports, __webpack_require__) {
    "use strict";
    Object.defineProperty(exports, "__esModule", {
        value: !0
    });
    const utils_1 = __webpack_require__(5);
    exports.Product = class {
        constructor(contract) {
            this.id = utils_1.Utils.getResourceName("products", contract.id, "shortId"),
            this.name = contract.name,
            this.displayName = contract.properties.displayName,
            this.description = contract.properties.description,
            this.approvalRequired = contract.properties.approvalRequired,
            this.state = contract.properties.state,
            this.subscriptionRequired = contract.properties.subscriptionRequired,
            this.subscriptionsLimit = contract.properties.subscriptionsLimit,
            this.terms = contract.properties.terms
        }
    }
}
```

![image](https://user-images.githubusercontent.com/2357647/82036750-f444a400-96a9-11ea-92c0-6a84d5485c5a.png)

![image](https://user-images.githubusercontent.com/2357647/82036771-fa3a8500-96a9-11ea-816f-3dda1a3de354.png)

**Comment by MiikaAntila** [comment]
We have the exact same issue with the new portal which occurs in all of our managed apim instances. Chrome browser shows the same error: 
Uncaught (in promise) TypeError: Cannot read property 'displayName' of undefined
    at new exports.Product (theme.js:2)

**Comment by nluff80** [comment]
We have also noticed this issue and it seems have occurred within the last week or so - I have a version of the New Developer Portal which is working fine but another version to which updates where published recently which shows this issue.

**Comment by azaslonov** [comment]
Hi everyone, the issue has been addressed and the fix merged. For the managed version, the release is in progress.

**Comment by nluff80** [comment]
Hi @azaslonov - when will the fix for managed version been released?

**Comment by azaslonov** [comment]
Most of the regions should be updated this week, the rest of them by the end of next week.

**Comment by JanneMattila** [comment]
Yes I can confirm that it works for me as well. Just remember to "Publish" the developer portal.

**Comment by mploksvenningsen** [comment]
This still doesn't work in our instance. It is located in North Europe.

Any news on the rollout?

**Comment by JanneMattila** [comment]
Did you @mploksvenningsen remember to publish the developer portal:
![image](https://user-images.githubusercontent.com/2357647/83617630-07081580-a592-11ea-94d0-7016d64cc7c6.png)

**Comment by mploksvenningsen** [comment]
I did, multiple times
