### ISSUE TITLE
Still need to refresh the page to accesss account after login via SSO

### ISSUE THREAD

**Issue by CoumbaNDI** [Azure/api-management-developer-portal#957]
We currently have an issue on our production environnement. After using our SSO to log in the APIM, the client need to refresh the page to be able to have access to his authenticated page.

1.Go to ' www.apimprod.com/signin-sso?token=e5fad947-7429-4b8b-84bf-539138d767cf&202009271444&EMDxjniUi4DZTDXLQ1knV'
2.Land on the page 'www.apimprod.com'
3.Refresh page 'www.apimprod.com'

Would like to access to authenticated page

Do you have any idea when this issue will be fix, we are located in France.

**Comment by mikebudzynski** [comment]
Can you explain the actual behavior vs expected behavior?

**Comment by azaslonov** [comment]
That should be fixed. Have you re-published the portal by chance?

**Comment by CoumbaNDI** [comment]
After login via SSO, i come back to the home page and I need to refresh the page to access my personal account.
I would like after connecting via SSO to accees my personal account without the need to refresh the page.

I do not have any message on the portal overview tab tell me that my portal isn't up to date. However, I republished the portal and the bug is still present.

**Comment by CoumbaNDI** [comment]
Are you guys investigating on this bug ?

**Comment by azaslonov** [comment]
Hi @CoumbaNDI, sorry for delay, I can't reproduce this issue, but looking at the way you form the URL, I think that you forget to URL encode the token, because I see "&" in it which is a concatenation character.
www.apimprod.com/signin-sso?token=e5fad947-7429-4b8b-84bf-539138d767cf&202009271444&EMDxjniUi4DZTDXLQ1knV

Valid URL should looke like this
`/signin-sso?token=azaslonov%26202011061947%266sK1aGWJn8lJxgdUQnFjA4L2LEnhH9ujZmYS7IYy14awB%2FjgcKJ1b4GMXItyGkDpn8xJsosSTzj6m6wteiPgTw%3D%3D`

The same goes to `returnUrl` parameter: `...&returnUrl=%2Fapi-details%23api%3Dbook-store-api`

**Comment by CoumbaNDI** [comment]
Thank you Alexander, thank to your help we managed to find the issue, you were right !

**Comment by azaslonov** [comment]
So encoding it is. Thanks for confirmation, I'm glad you guys figured this out.

I'm closing the issue then.
